// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/RipperAcskt/innotaxianalyst/internal/service (interfaces: GRPCService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	proto "github.com/RipperAcskt/innotaxi/pkg/proto"
	client "github.com/RipperAcskt/innotaxianalyst/internal/client"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockGRPCService is a mock of GRPCService interface.
type MockGRPCService struct {
	ctrl     *gomock.Controller
	recorder *MockGRPCServiceMockRecorder
}

// MockGRPCServiceMockRecorder is the mock recorder for MockGRPCService.
type MockGRPCServiceMockRecorder struct {
	mock *MockGRPCService
}

// NewMockGRPCService creates a new mock instance.
func NewMockGRPCService(ctrl *gomock.Controller) *MockGRPCService {
	mock := &MockGRPCService{ctrl: ctrl}
	mock.recorder = &MockGRPCServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGRPCService) EXPECT() *MockGRPCServiceMockRecorder {
	return m.recorder
}

// GetJWT mocks base method.
func (m *MockGRPCService) GetJWT(arg0 context.Context, arg1 uuid.UUID) (*client.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJWT", arg0, arg1)
	ret0, _ := ret[0].(*client.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJWT indicates an expected call of GetJWT.
func (mr *MockGRPCServiceMockRecorder) GetJWT(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJWT", reflect.TypeOf((*MockGRPCService)(nil).GetJWT), arg0, arg1)
}

// GetOrdersQuantity mocks base method.
func (m *MockGRPCService) GetOrdersQuantity(arg0 context.Context, arg1 client.AnalysType) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrdersQuantity", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrdersQuantity indicates an expected call of GetOrdersQuantity.
func (mr *MockGRPCServiceMockRecorder) GetOrdersQuantity(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrdersQuantity", reflect.TypeOf((*MockGRPCService)(nil).GetOrdersQuantity), arg0, arg1)
}

// SetRating mocks base method.
func (m *MockGRPCService) SetRating(arg0 context.Context, arg1 *proto.Rating) (*proto.Empty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRating", arg0, arg1)
	ret0, _ := ret[0].(*proto.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetRating indicates an expected call of SetRating.
func (mr *MockGRPCServiceMockRecorder) SetRating(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRating", reflect.TypeOf((*MockGRPCService)(nil).SetRating), arg0, arg1)
}
